module.exports = {
  projectId: '',
  projectName: '',
  version: '',
  url: '',
  token: '',
  batchSize: 10,
  username: '',
  password: '',
  publish: true,
  dir: false,
  checkQualityGate: false,
  checkQualityGateLocal: false,
  checkQualityGateTimeout: 10000,
  checkQualityGateDefaultDelay: 2000,
  checkQualityGateEnvironments: '',
  jUnitReporter: false,
  jUnitReporterPath: 'contract-tests-junit.xml',
  _session_token: '',
  _analysis_id: ''
}